name: 'Greetings'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations, @${{ github.actor }}! 🎉 Thank you for creating your issue for Moksh. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work! Should you have any queries or require guidance, do not hesitate to ask.'
          pr-message: 'Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request for Moksh. Our dedicated team will review it diligently.Your contribution is valuable and we appreciate your efforts to improve our project.'
